name = "metalogica_lean_project"
version = "0.1.0"
defaultTargets = ["metalogica_project"]

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4"

[[lean_lib]]
name = "metalogica_lean_project"

[[lean_exe]]
name = "metalogica_project"
root = "Main"
